group_import_csv_configs:
  id:
      header: ID
      validate:
        - nullable
        - numeric
        - digits_between:1,2147483647
  name:
      header: Group Name
      validate:
        - required
        - string
        - max:255
  note:
      header: Group Note
      validate:
        - string
  group_leader_id:
      header: Group Leader
      validate:
        - required
        - numeric
        - digits_between:1,2147483647
        - exists:user,id
  group_floor_number:
      header: Floor Number
      validate:
        - required
  deleted_date:
      header: Delete
      validate:
        - nullable
      